## 21/09/2026
Recaping to date, I have:

* Set up labbook
* Set up code repository locally
* Received code and basic introduction from Dr Turci
* Partly read introductory papers/books on the topic

Looking forwards, there are 2 more immediate things i need to do:

* continue reading to build up understanding:
	* Second quantisation [@secondQuantisationBook2010]
	* Introductory paper [@OpenQuantumSystemsIntro2012]
* Build up main "computational engine":
	* Look through and understand code Dr Turci has sent me
	* Refactor said code into a convenient utility I can use throughout this project

After i've done these i'll be equiped with the main theoretical and computational tools for this project. This will inform the rest of the investigation of this project.

Having a practical understanding of what this project entails should help me understand the theory "in context". As such, i think for now its worth examining the code Dr Turci has sent me, in order to start planning the computational engine.


Examining the provided julia code (Y4DissertationCodeMaterials/providedCode/basic-1site-bath-julia.ipynb), it starts by reiterating the maths.
Note; explanation recommends finding a good explanation for "wick's theorem". Examining my old personal notes for QFT, i recall it being relevant to evaluating the non commuting terms in the Dyson series. That understanding was based on [@NoNonsenseQFT] which may be of use. However i wonder if the second quantisation [@secondQuantisationBook2010] chapter will introduce it in a more contextually relevant manner.
Skimming the chapter it seems so...
Changed my mind, i'm going to try and quickly skim the chapter with the remainder of this afternoon. I expect the concepts will be familiar, so shouldn't take too long. Code examination can come tmr.

### Reading notes: Second quantisation impressions [@secondQuantisationBook2010]:

Second quantisation seems to be general framework of ladder operators and associated commutation relations; which is a familiar concept. Apparently generalises nicely to N-body quantum physics.

Chapter motivates second quantisation by highlighting computational issues w/many body QM due to indistinguishablity, symmetrization.antisymmetrization, and the exchange of particle numbers.

#### Second quantisation basics
It then covers the "apparatus of second quantization".

Compares representation of labelling particles in state individually to simply counting the number of particles in each state (I.E $\ket{1, 1, 1, 1, 2, 2, 3}$ becomes $\ket{4, 2, 1}$). This is the "occuptation number representation". Also note the "Fock space" $\mathcal{F}$; made up of basis states $\{ \ket{n_{i}} \}$ w/out occupation num condition $\sum n_i = N$. Therefore many body state can be represented as $\ket{\Psi}=\sum_{n_{i}} c_{n_i}\ket{n_{i}}$.

Within this framework, ladder operators can be constructed to act on $\mathcal{F}$:

$a_{i}^{\dagger}\ket{n_{1},...,n_{i},...}=(n_{i}+1)^{1/2}\zeta^{s_{i}}\ket{n_{1},...n_{i}+1,...}$
$s_{i}=\sum_{j=1}^{i-1}n_{j}$

Note that in the fermionic case, the $n_{i}+1$ operation is a mod 2 operation $n_{i}+1 \equiv (n_{i}+1)\%2$
Utility of this; can generate all states by repeated application of $a_{i}^{\dagger}$ to vacuum state:

$\ket{n_{1},...}=\prod_{i}\frac{1}{(n_{i}!)^{1/2}}(a_{i}^{\dagger})^{n_{i}\ket{0}}$

::: {.column-margin}
Wierd notation used by chapter for commutation/anti-commutation relations:

$[A,B]_{\zeta}=AB-\zeta AB$

$[A,B]_{\zeta=+1}=[A,B]_{+}=AB-AB$ // commutator

$[A,B]_{\zeta=-1}=[A,B]_{-}=AB+AB=\{A,B\}$ // anticomutator
:::

Note that:

$[a_i,a_j^{\dagger}]_{\zeta}=\delta_{ij}$

$[a_i,a_j]_{\zeta}=0$

$[a_i^{\dagger},a_j^{\dagger}]_{\zeta}=0$

#### practical aspects:
The chapter continues into the "practical aspects" of this framework.

::: {.callout-note title="Single particle base transforms"}
Firstly; switching between single particle bases $\{ \lambda \} \to \{ \widetilde{\lambda} \}$ - the operators transform as:

$a_{\widetilde{\lambda}}^{\dagger} = \sum_{\lambda}\braket{\lambda|\widetilde{\lambda}}a_{\lambda}^{\dagger}$

$a_{\widetilde{\lambda}} = \sum_{\lambda}\braket{\widetilde{\lambda}|\lambda}a_{\lambda}$

where $\lambda$ represents a particular particle state in a particular single particle basis.
For continuous quantum numbers (I.E, pos) the sum becomes integrals as:

$a_{\lambda}=\int_{0}^{L}dx\braket{\lambda|x}a(x)$

$a(x)=\sum_{k}\braket{x|\lambda}a_{\lambda}$
:::

::: {.callout-note title="Single particle operators"}
Secondly operators acting on single particles w/single party operator $o_{n}$ on nth particle typically become $\mathcal{O_{1}}=\sum_{n=1}^{N}o_{n}$.

Typical example noted is momentum:
$T=\sum_{n}\frac{p_{n}^2}{2m}$

Also introduces "occupation number operator" which counts #particles in state:

$n_{\lambda}=a_{\lambda}^{\dagger}a_{\lambda}$

Which is useful for actually constructing $\mathcal{O_{1}}$. Given $o=\sum_{i}o_{\lambda_i}\ket{\lambda_i}\bra{\lambda_i}$, $o_{\lambda_i}=\braket{\lambda_i | o | \lambda_i}$. Skipping over details i'm uninterested in rn, the general result is:

$\mathcal{O_1}=\sum_{\mu\nu}\braket{\mu |o|\nu}a_{\lambda}^{\dagger}a_{\lambda}$
:::

The chapter then goes into concrete examples to cement these ideas - not immediately relevant, but earmarking p48 in case useful for later.


#### skimming rest of chapter

There's also a practical applications section. Not going to go into that in depth; skimming to try to earmark anything of use:

* Electrons in a periodic potential (goes through nearly free electrons -> tight binding)(p51)
* Mott-hubbard transition and the magnetic state (p61)
* interacting fermions in one dimension (p67)
	* this section starts using ideas of interaction vs non interacting terms - i suspect wicks theorem (and other useful bits) may be here
* Quantum spin chains (76)
* Summary and outlook - Ch summary (p83)

Wick theorem is not in this section - its mentioned in the summary.
ctrl+f through the book doesn't seem to have a contained explanation albeit many uses of Wick's theorem.
In which case [@NoNonsenseQFT] may be a better call - the mathematical machinery seems to generalize beyond QFT, so it should be applicable. Ctrl+f through [@NoNonsenseQFT], the explanation of contractions/Wick's theorem goes between p426-p428 at minimum (more after that). Not a today thing to look at but worth earmarking for later.

This reading was a useful refresher and "earmarking exploration" - i think tmr i can go through the code in depth to understand what its doing/how its structured. I should be able to come up with a near term plan thereafter (wether i can get on w/the computational engine or if i need more reading).



## 22/09/2026
Going to look through the code Dr Turci sent me.
I think task list is:

* Read through code and break down what its doing
* Compare the julia vs python code - quick runtime benchmark should show Julia to be faster, thus justifying its use
* think about how to rewrite the simulation into a utility that can be used for the rest of the project:
	* Assuming Julia's faster, write the simulation code in Julia
	* If needbe, can export the simulation results, and build a python julia handler - that way the julia sim is smth that can be called from python code as its own utility

### Examining provided code:
First code block is just some library setup.

Second code block sets up spectral function (currently set to a semi-circle) as function of $\omega$. It then initialises an empty 2D hamiltonian array for the bath sites. Unsure why 2D; my understanding is that a 1D list would encapsulate the bath perfectly fine. Potentially initialising all timesteps and fills them throughout the sim? Oooooh, nvm, its the hamiltonian matrix.
Plots the spectral function over $\omega$.

::: {.column-margin}
Sidenote; just realized Julia indicates vector maths using a "." notation (I.E, scalar addition ```a+b``` becomes vector addition ```a.+b```)
:::

Third code block sets up initial state using Fermi Dirac stats: 

$\mathcal{f}(\beta, \mu, E) = \dfrac{1}{1+e^{\beta E-\beta\mu}}$

The simulation assumes no initial correlations; therefore initial correlation matrix is diagonalised and filled with $\mathcal{f}(\beta, \mu, E)$ for all corresponding system and bath sites:

$C_{ii} = \mathcal{f}(\beta, \mu, E_i)$

Third code block sets up this initial correlation matrix.

Fourth/fifth code blocks illustrate fact that $C_{t=0}$ is diagnolized in site, not hamiltonian basis.

Sixth/seventh code block builds unitary time evolution:

$U(t) = e^{-iHt}$

And build function to evolve correlation matrix over time t.
::: {.column-margin}
Sidenote; another julia syntax note; matrix complex conjugate is indicated as ```H'```
:::

Code block 9 (and surrounding commented out code blocks) compute the correlation matrix over a range of times. The commented out bits inc a computationally slower algorithm (the main method is iterative), and a commented out plot.

Code blocks 10, 11 compute and plot the reduced density matrix element corresponding to the occupation of the system. Recalling [@ProjectOutline2026], the reduced density matrix follows:

$\rho_S(t)=(\begin{array}{cc}
1-\mathbf{C}_{11}(t) & 0 \\
0 & \mathbf{C}_{11}(t)
\end{array})$

where the first element corresponds to the system.

Code block 12 computes the occupation for the bath at the end of the sim.

Final section asks the following questions:

#### On convergence

* How does the convergence depend on the quality of the time discretisation
* How does it truly depend on the number of bath sites (on CPU and GPUs)?
* How does it depend on alternative choices of the initial state
* How does it compare with alternative methods (e.g. the matrix product state (MPS) approach)? 

#### On the physics

* What happens to the covariance matrix as we time evolve? Does it show any emergent structure? 
* How do these structures relate to the initial choice of the spectral function?
* Let's perturb the spectral function: can we see long-lived memory effects building up?

Which seem to be starting points for my investigations.

IMPORTANT NOTE: The python version of the code also includes some additional stuff; a version of the code which uses pytorch for GPU acceleration. Does the same process, but using pytorch for the matrix multiplications. This may be faster; will thus need to compare julia, base python, pytorch accelerated python.

### thoughts on the code
The code is written in a very "linear" manner - good to illustrate the computational process, less useful as a project utility; rewriting it into a self contained utility that can be called by other code will be useful. Before that however, it'll be useful to quickly copy/paste the code into julia/py files, run and time em for benchmarking reasons.

Am quickly copying over the code to dedicated julia/py files. the py file also has the pytorch stuff commented out for the moment. Going to test the timings for all three; currently just making sure the 3 codes run. Going to comment out all print statements since ik in python that can slow things down; and the main simulation engine wouldn't have print statements built in anyhows.
The rough timings follow:

* Julia: 108.98370599746704 sec
* Python: 74.38792300224304 sec
* pytorch: 56.157703161239624 sec

Thats odd and counterintuitive. Going to repeat both tests to make sure its not a fluke.

* Julia: 105.68335008621216 sec
* Python: 64.68177103996277 sec
* pytorch: 31.687152862548828 sec


That is odd... Quick lookup, this [@juliaVsPythonPerformance] explainer notes that generally Julia is faster as it is a C based compiled language whilst python is an interpretive language. However, certain python libraries (notably numpy) are written in C so have similar performances. As such, if using those C based python libraries, python can be almost as fast as julia. However that doesn't explain the significant discrepancy in results here.

Have fiddled with vscodium's julia settings; initially it was using an auto #threads, have set it to 8 for now to see if that makes a diff. Seems to not make a difference; have set the value to auto. Doesn't make a difference... Trying again with 16 threads, but have restarted the terminal; double check that that hasn't been overlooked. Ok that fixed it to some degree producing:

* Julia: 60.03582501411438 sec

Which is roughly on par w/python; although pytorch still outperforms it significantly.

Thinking of other potential issues, either there are some tasks that Julia is worse at (I.E, i wonder if plotting is as efficient), or the julia code isn't fully optimised whilst the python code makes efficient use of the numpy/pytorch libraries.

Going to comment out the plotting code in both, compare the speed therein:

* Julia: 45.252466917037964 sec
* Python: 45.61387276649475 sec
* Pytorch: 27.66377019882202 sec

Sidenote; when running the python code, my laptop's fan is SIGNIFICANTLY louder than when running the Julia code. I may have a look and see my system resource use; cause that may give further insight into wether or not the above is a fair comparison, or if there are further optimisations that could be made to Julia. 

Have pulled up ```top``` in terminal, This is a non rigorous test, however the cpu usage for the 3 options peaks at:

* Julia: 798 %cpu - 39.82936978340149 sec - #threads: 43/8
* Python: 746 %cpu - 41.40748572349548 sec - #threads: 18/8
* Pytorch: 767 %cpu - 27.51361894607544 sec - #threads: 27/8

hmmmmmm... This quick test implies that Julia uses the most CPU resources, yet performs the worst...
There where 1 or 2 lines of julia code i didn't quite comment out when commenting out the plotting stuff; i doubt it has much of an effect but repeating the timing tests:

* Julia: 44.23794388771057 sec

Effectively no difference...

Am building quick test algorithm in both julia and python:

* define basic addition function f(x,y) = x + y
* start timer
* initiate 2 arrays 1000 elements long from 0-10000
* add the 2 together into an output array
* end timer

* Julia: 0.008497953414916992
* python: 0.0000841617584229


odd... Excluding the array construction from the time:

* Julia: 0.006654024124145508
* python: 0.0000829696655273

Not much of a difference. Note however, when instead of '''x+y''' '''x.+y''' the time jumps an order of magnitude...

THis leads me to believe that the julia code may be poorly optimised especially since its being compared to numpy and and scipy implementations.
[@juliaPerformanceTips] is an article detailing how to get most out of Julia so will have a quick look through there.

#### julia performance tips reading [@juliaPerformanceTips]

* performance critical code should be inside functions
* avoid unsigned global variables

Tried [@stackoverflowJuliaVsPython2022] moving everything into a function in case that worked; it didnt. However i suspect that the code requires broader optimisation. The fact that the basic adding arrays test favours python so strongly is incredibly odd... Apparently global variables are REALLY bad in julia, so maybe its that?

Have just measured the one case where there is a global variable and thats the issue.
THis block of code:
```
Udt = unitary(dt)
    UdtT = Udt'
    Css = Dict(0.0 => C0)
    key = 0.0
    for t in times[2:end]
        #println(key, " ",t)
        Css[t] = Udt * Css[key] * UdtT
        key = t
    end
```
is whats causing issues